---
cluster:
  name: "<CLUSTERNAME>"

node:
  name: "<HOSTNAME>"
  max_local_storage_nodes: 3

network:
  host: 127.0.0.1

http:
  host: 0.0.0.0
  port: 9200
  # Disabled https compression to mitigate BREACH attacks
  compression: false

discovery:
  type: single-node

bootstrap:
  memory_lock: true

plugins:
  security:
    ssl:
      http:
        # REST layer (“HTTPS”) encryption
        enabled: true
        pemcert_filepath: private/host.crt
        pemkey_filepath: private/host.key.pkcs8
        pemtrustedcas_filepath: private/ca-certificates.crt
        truststore_filepath: private/cacerts
        enabled_protocols: ["TLSv1.2", "TLSv1.3"]

      # Inter-node encryption
      transport:
        pemcert_filepath: private/host.crt
        pemkey_filepath: private/host.key.pkcs8
        pemtrustedcas_filepath: private/ca-certificates.crt
        enforce_hostname_verification: true
        # ldap requires java truststore 
        truststore_filepath: private/cacerts
        enabled_protocols: ["TLSv1.2", "TLSv1.3"]

    # Initialize the security configuration automatically on startup
    allow_default_init_securityindex: true

    # These TLS certificate should be granted full access rights for the cluster
    authcz:
      admin_dn: ["<SUPER_ADMIN_DN>"]
    audit:
      type: internal_opensearch
    enable_snapshot_restore_privilege: true
    check_snapshot_restore_write_privileges: true
    restapi:
      roles_enabled: ["all_access", "security_rest_api_access"]
    system_indices:
      enabled: true
      indices: 
        - ".plugins-ml-model"
        - ".plugins-ml-task"
        - ".opendistro-alerting-config"
        - ".opendistro-alerting-alert*"
        - ".opendistro-anomaly-results*"
        - ".opendistro-anomaly-detector*"
        - ".opendistro-anomaly-checkpoints"
        - ".opendistro-anomaly-detection-state"
        - ".opendistro-reports-*"
        - ".opensearch-notifications-*"
        - ".opensearch-notebooks"
        - ".opensearch-observability"
        - ".opendistro-asynchronous-search-response*"
        - ".replication-metadata-store"
