---
name: "samba_smb_<BASENAME-OF-SHARE>"
fs:
  url: "<PATH-OF-SHARE>"
  excludes:
    - "*/lost+found"
    - "*/[.]*"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  attributes_support: false
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: true
  ocr:
    enabled: false
    language: "eng"
    pdf_strategy: "ocr_and_text"
  follow_symlinks: false

elasticsearch:
  index: "samba_smb"
  folder_index: "samba_smb_folder"
  username: "local_fscrawler"
  password: "<OPENSEARCH-LOCAL-FSCRAWLER-PW>"
  ssl_verification: true
  nodes: [url: "https://<OPENSEARCH-FQDN>:9200"]
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "10mb"
